### ISSUE TITLE
Oopsie when trying to load AGUnit

### ISSUE THREAD

**Issue by ghost** [sdekock/AgUnit#4]
[Window Title]
ReSharper Test Runner

[Main Instruction]
Unit Test Runner failed to load test assembly

[Content]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows, Version=5.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. The system cannot find the file specified.

[^]  

[Buttons]
   [Header=_OK, Content=] 

[Expanded Information]
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at NUnit.Core.CoreExtensions.InstallAdhocExtensions(Assembly assembly)
   at NUnit.Core.Builders.TestAssemblyBuilder.Load(String path)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, Boolean autoSuites)
   at NUnit.Core.Builders.TestAssemblyBuilder.Build(String assemblyName, String testName, Boolean autoSuites)
   at NUnit.Core.TestSuiteBuilder.Build(TestPackage package)
   at NUnit.Core.SimpleTestRunner.Load(TestPackage package)
   at NUnit.Core.ProxyTestRunner.Load(TestPackage package)
   at NUnit.Core.RemoteTestRunner.Load(TestPackage package)
   at JetBrains.ReSharper.UnitTestRunner.nUnit.NUnitTaskRunner.ExecuteRecursive(TaskExecutionNode node)

**Comment by sdekock** [comment]
Do you have the Silverlight 5 developer runtime installed ?
AgUnit currently requires it, even for Silverlight 4 projects.

**Comment by ghost** [comment]
I have the SL5 sdk and am building an SL5 project.

**Comment by sdekock** [comment]
It looks like the ReSharper NUnit runner is running your tests, not AgUnit.

Can you confirm AgUnit is installed correctly ?
You can check this by going to the ReSharper Options screen and looking under the Plugins section.

Are you using anything other versions than the following ?
Visual Studio 2010 SP1
Silverlight 5 Tools for Visual Studio 2010 SP1
ReSharper 6.1.1 (Build 6.1.1000.82)
AgUnit 0.5 (pre-release) (from GitHub downloads)

I'm releasing a new version of AgUnit tomorrow, let me know if that solves of your issue.

**Comment by sdekock** [comment]
This may actually be related to the "Unblock" issue.

Please check that all files are unblocked.
You can do this by right clicking the file (AgUnit.Runner.Resharper61.dll, ...) and choosing properties.
If you're seeing an Unblock button, then the files are blocked.

You can unblock each file individually, but it's easier to download the zip file again and Unblock the zip file before extracting it.

**Comment by ghost** [comment]
I'm usually unblocking dlls as soon as I download them, bit I'll check both
options tomorrow morning.
Thanks for your ideas.

**Comment by ghost** [comment]
It seems that I had more than one AgUnit plugin recognized by ReSharper. Cleaned and now successfully loads and runs the tests.
However, while those tests pass under pure StatLight 1.6.4375, they fail under AgUnit.
I'm getting this exception (when building the IoC Container):

{System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Controls, Version=5.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The requested assembly version conflicts with what is already bound in the app domain or specified in the manifest. (Exception from HRESULT: 0x80131053)
File name: 'System.Windows.Controls, Version=5.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'}

Which leads me to believe that AgUnit is forcibly loading System.Windows.Controls from the "wrong" place. Could it be?

**Comment by sdekock** [comment]
Do you have "Copy Local" turned on for System.Windows.Controls ?

**Comment by ghost** [comment]
Yes. Then I added the reference to the tests project, too, and that didn't help either.

While I'm unsure what the StatLight XAPs actually do, I think I suspect the wrong ones are being used for the SL5 project. Does that make any sense?

**Comment by sdekock** [comment]
I believe "Copy Local" should be turned off for System.Windows.Controls because it's a Silverlight runtime assembly (not SDK).

The StatLight XAPs are templates that contain the StatLight test harness and the runners for your test framework.
Your own test assemblies with dependencies are added to a temporary XAP based on these template XAPs.

**Comment by ghost** [comment]
Turned on, and off, and up, and sideways, and nothing changed. 
Yes, I rebuilt. :)

**Comment by sdekock** [comment]
I've just tried creating a project with both "Copy Local" on and off, and they both worked without issue.
It was true by default, which I find very strange ...

I believe the problem is you're getting another version of the System.Windows.Controls.dll from somewhere.
A version that doesn't match the one from the Silverlight 5 runtime.

StatLight seems to include the System.Windows.Controls.dll in it's XAP file.

I believe these are the dll's from the Silverlight 5 RTM build (5.0.61118.0).
That is the version I have installed on my dev machines (Silverlight 5 RTM developer runtime).

Is your runtime upgraded to 5.1.10411.0 (5 Security Update) or do you have the client runtime installed instead of the developer runtime ?
You can check here: www.microsoft.com/getsilverlight/

Here's the list of Silverlight versions for future reference: http://en.wikipedia.org/wiki/Microsoft_Silverlight_History

I'll try to contact staxmanade from StatLight and investigate why the System.Windows.Controls.dll is included in the XAP.

**Comment by staxmanade** [comment]
The dll was originally included because the MSFT Silverlight Testing Framework took a dependency on it for things like the TreeView control (at least I thought so). I've removed it locally and my build/tests all pass. So I'm not sure exactly what's going on. I've removed it in the code and pushed my changes up. After pulling these in, let me know if this works out...

**Comment by ghost** [comment]
I'm running 5.1. Installed a couple on weeks ago.

I tried to add new XAPs from the StatLight 1.6 package, but it seems that either AgUnit or StatLight do not iterate over all XAPs in the folder (ProcMon), so that did me no good. Then I dissected the "latest" XAP (June2011) in the AgUnit folder, removed the Controls.dll, updated the manifest (and changes the runtime version) and still nothing.
If you have any more ideas I'l be happy to try them out.

**Comment by sdekock** [comment]
I'll try upgrading my dev machine.

Did you try reproducing this issue in a new/empty project? Could you send it to me somehow?
And I see you're using NUnit, can you tell me where you got the binaries from? Because there are a lot of different versions going around ... some of them just don't work.

**Comment by ghost** [comment]
I'll try to repro. No luck so far.

What's worth re-iterating is that
1) those tests do run and pass on pure StatLight.
2) The tests _run but fail_ at a Caliburn-Autofac-MyCode nexus. There may be explicit assembly loading there by Autoaac (though I couldn't find it myself).
3) The error has to do with the wrong assemblies being loaded.

**Comment by ghost** [comment]
Oopsie resolved on Re# v7 and AgUnit v0.6
