### ISSUE TITLE
How can I enable ElevatedPermissions for my tests?

### ISSUE THREAD

**Issue by dittodhole** [sdekock/AgUnit#6]
Hi!

I am using AgUnit for implementing tests against my project sharpLightFtp (https://github.com/dittodhole/sharpLightFtp), and hence I am doing socket programming, I'll need ElevatedPermissions for my tests.
In a Silverlight Application I can simply set it, but how can I enable this for my tests?

**Comment by sdekock** [comment]
AgUnit uses StatLight (http://statlight.codeplex.com/) under the covers.
As far as I know it doesn't support out of browser / elevation.
See: http://statlight.codeplex.com/workitem/12983

**Comment by dittodhole** [comment]
Actually my test-project (https://github.com/dittodhole/sharpLightFtp/blob/master/sharpLightFtp.Test/sharpLightFtp.Test.csproj) uses `<RequireInBrowserElevation>true</RequireInBrowserElevation>` - any information on that?

**Comment by sdekock** [comment]
I was suggesting out of browser because it requires less configuration for elevation.

Right now, you will need to make a custom build of StatLight (there's no option to enable this), if you drop it in the AgUnit folder it should keep working.

In StatLight you will have to configure the test harnass (Silverlight project) with the in-browser elevation settings.

**Comment by dittodhole** [comment]
Thanks for clarification!
