### ISSUE TITLE
ReSharper8 branch - devenv.exe won't quit on VS close

### ISSUE THREAD

**Issue by mhoyer** [sdekock/AgUnit#7]
Nice to already see an attempt for R#8 support in AgUnit. But I trapped into an issue with the current branch:

After I ran some unit tests with the runner and try to close VS2012 the devenv.exe process won't exit.

Anyone else having this? Any ideas how to fix this?

I checked with: R# 8.0.14.856 on VS2012 11.0.60610.1

**Comment by sdekock** [comment]
It might be because the test runner has thrown an exception and won't close.
They changed this behavior in R# 8 and I'm still investigating it.
It used to be an external process (.exe) that was started for each test run, but I don't see it in task manager anymore.

The logging from R# may help:
Start visual studio (from command line) with: _devenv.exe /ReSharper.LogFile "C:\resharper.log" /ReSharper.LogLevel Verbose_
This should create a logfile in C:\resharper.log.

**Comment by sdekock** [comment]
Fixed in the 0.8 release.
